instruction = [
    """
    You will be provided with a paragraph prefixed by "TEXT:". Your task is to perform the following task of finding terms based on the instructions below.
    - Provide a list of chemical substances, which can be either pure chemicals or chemical compounds.
    - Do not add additional words or groups of words to chemical substances that do not originally appear with them. 
    - Do not split chemical substances into two parts if they contain "and" or "or" within them.
    - Preserve the original capitalization of chemical substances, maintaining both lowercase and uppercase letters as they appear.
    - Retain any <super></super> or <sub></sub> tags if they are found in chemical substances.
    - Provide the chemical substances found in the paragraph as a Python dictionary, where "chemical" is the key of the dictionary and the value of the dictionary is a list of chemical substances. If no chemical substances are found, return an empty list as value.
    - Keep all occurrences of chemical substances in the list if they appear multiple times.
    - Maintain the sequence of appearance of chemical instances in the list, ensuring that the first encountered chemical substance appears first.
    """,
    """
    You will be provided with a paragraph prefixed by "TEXT:". Your task is to perform the following task of finding terms based on the instructions below.
    - Provide a list of material substances, which are mixtures that are either solid materials or fluids.
    - Do not add additional words or groups of words to material substances that do not originally appear with them. 
    - Do not split material substances into two parts if they contain "and" or "or" within them.
    - Preserve the original capitalization of material substances, maintaining both lowercase and uppercase letters as they appear.
    - Retain any <super></super> or <sub></sub> tags if they are found in material substances.
    - Provide the material substances found in the paragraph as a Python dictionary, where "material" is the key of the dictionary and the value of the dictionary is a list of material substances. If no material substances are found, return an empty list as value.
    - Keep all occurrences of material substances in the list if they appear multiple times.
    - Maintain the sequence of appearance of material instances in the list, ensuring that the first encountered material substance appears first.
    """,
    """
    You will be provided with a paragraph prefixed by "TEXT:". Your task is to perform the following task of finding terms based on the instructions below.
    - Provide a list of terms that describe the characteristic way of how a material entity is internally physically or chemically arranged. These structural components may themselves be used to build up larger material entities via chemical or physical bonding.
    - Do not add additional words or groups of words to terms that do not originally appear with them. 
    - Do not split terms into two parts if they contain "and" or "or" within them.
    - Preserve the original capitalization of terms, maintaining both lowercase and uppercase letters as they appear.
    - Retain any <super></super> or <sub></sub> tags if they are found in terms.
    - Provide the terms found in the paragraph as a Python dictionary, where "structure" is the key of the dictionary and the value of the dictionary is a list of terms. If no terms are found, return an empty list as value.
    - Keep all occurrences of terms in the list if they appear multiple times.
    - Maintain the sequence of appearance of terms in the list, ensuring that the first encountered terms appears first.
    """,
    """
    You will be provided with a paragraph prefixed by "TEXT:". Your task is to perform the following task of finding terms based on the instructions below.
    - Provide a list of terms that describe an attribute, quality, or characteristic of chemicals, materials, or structures.
    - Do not add additional words or groups of words to terms that do not originally appear with them. 
    - Do not split terms into two parts if they contain "and" or "or" within them.
    - Preserve the original capitalization of terms, maintaining both lowercase and uppercase letters as they appear.
    - Retain any <super></super> or <sub></sub> tags if they are found in terms.
    - Provide the terms found in the paragraph as a Python dictionary, where "property" is the key of the dictionary and the value of the dictionary is a list of terms. If no terms are found, return an empty list as value.
    - Keep all occurrences of terms in the list if they appear multiple times.
    - Maintain the sequence of appearance of terms in the list, ensuring that the first encountered terms appears first.
    """,
    """
    You will be provided with a paragraph prefixed by "TEXT:". Your task is to perform the following task of finding terms based on the instructions below.
    - Provide a list of terms that describe a product that is commercially sold, it could either be an end product (e.g., printing paper, toilet paper, medication, etc.) which are typically associated with particular uses, or an intermediate product of interest to specific industries (e.g., tissue paper, films, insulation, etc.).
    - Do not add additional words or groups of words to terms that do not originally appear with them. 
    - Do not split terms into two parts if they contain "and" or "or" within them.
    - Preserve the original capitalization of terms, maintaining both lowercase and uppercase letters as they appear.
    - Retain any <super></super> or <sub></sub> tags if they are found in terms.
    - Provide the terms found in the paragraph as a Python dictionary, where "application" is the key of the dictionary and the value of the dictionary is a list of terms. If no terms are found, return an empty list as value.
    - Keep all occurrences of terms in the list if they appear multiple times.
    - Maintain the sequence of appearance of terms in the list, ensuring that the first encountered terms appears first.
    """,
    """
    You will be provided with a paragraph prefixed by "TEXT:". Your task is to perform the following task of finding terms based on the instructions below.
    - Provide a list of terms that describe any kind of manufacturing or experimental process, or processing technique (e.g., spinning or purification techniques) used to alter materials' properties or structure.
    - Do not add additional words or groups of words to terms that do not originally appear with them. 
    - Do not split terms into two parts if they contain "and" or "or" within them.
    - Preserve the original capitalization of terms, maintaining both lowercase and uppercase letters as they appear.
    - Retain any <super></super> or <sub></sub> tags if they are found in terms.
    - Provide the terms found in the paragraph as a Python dictionary, where "process" is the key of the dictionary and the value of the dictionary is a list of terms. If no terms are found, return an empty list as value.
    - Keep all occurrences of terms in the list if they appear multiple times.
    - Maintain the sequence of appearance of terms in the list, ensuring that the first encountered terms appears first.
    """,
	"""
	You will be provided with a paragraph prefixed by "TEXT:". Your task is to perform the following task of finding terms based on the instructions below.
    - Provide a list of terms that describe any kind of machine, device or other equipment used to process or measure materials during the processing or manufacturing of cellulosic materials.
    - Do not add additional words or groups of words to terms that do not originally appear with them. 
    - Do not split terms into two parts if they contain "and" or "or" within them.
    - Preserve the original capitalization of terms, maintaining both lowercase and uppercase letters as they appear.
    - Retain any <super></super> or <sub></sub> tags if they are found in terms.
    - Provide the terms found in the paragraph as a Python dictionary, where "equipment" is the key of the dictionary and the value of the dictionary is a list of terms. If no terms are found, return an empty list as value.
    - Keep all occurrences of terms in the list if they appear multiple times.
    - Maintain the sequence of appearance of terms in the list, ensuring that the first encountered terms appears first.
	""",
	"""
	You will be provided with a paragraph prefixed by "TEXT:". Your task is to perform the following task of finding terms based on the instructions below.
    - Provide a list of terms that describe a quantitative or qualitative measurement of something, typically specified with a measurement unit.
    - Do not add additional words or groups of words to terms that do not originally appear with them. 
    - Do not split terms into two parts if they contain "and" or "or" within them.
    - Preserve the original capitalization of terms, maintaining both lowercase and uppercase letters as they appear.
    - Retain any <super></super> or <sub></sub> tags if they are found in terms.
    - Provide the terms found in the paragraph as a Python dictionary, where "measurement" is the key of the dictionary and the value of the dictionary is a list of terms. If no terms are found, return an empty list as value.
    - Keep all occurrences of terms in the list if they appear multiple times.
    - Maintain the sequence of appearance of terms in the list, ensuring that the first encountered terms appears first.
	""",
	"""
	You will be provided with a paragraph prefixed by "TEXT:". Your task is to perform the following task of finding terms based on the instructions below.
    - Provide a list of terms that refers to a shortened form of a word or phrase (not including chemical formulas).
    - Do not add additional words or groups of words to terms that do not originally appear with them. 
    - Do not split terms into two parts if they contain "and" or "or" within them.
    - Preserve the original capitalization of terms, maintaining both lowercase and uppercase letters as they appear.
    - Retain any <super></super> or <sub></sub> tags if they are found in terms.
    - Provide the terms found in the paragraph as a Python dictionary, where "abbreviation" is the key of the dictionary and the value of the dictionary is a list of terms. If no terms are found, return an empty list as value.
    - Keep all occurrences of terms in the list if they appear multiple times.
    - Maintain the sequence of appearance of terms in the list, ensuring that the first encountered terms appears first.
	""",
]

example_10 = [
    """
    TEXT: Cellulose (C <sub>6</sub> H <sub>10</sub> O <sub>5</sub> ) <sub>n</sub> is one of the most ubiquitous organic polymers on the planet. It is a significant structural component of the primary cell wall of green plants, various forms of algae and oomycetes. It is a polysaccharide consisting of a linear chain of several hundred to many thousands of β(1 → 4) linked d-glucose units. There are various extraction procedures for cellulose developed by using different processes like oxidation, etherification and esterification which convert the prepared celluloses in to cellulose derivatives. Since it is a non-toxic, bio-degradable polymer with high tensile and compressive strength, it has widespread use in various fields such as nanotechnology, pharmaceutical industry, food industry, cosmetics, textile and paper industry, drug-delivery systems in treating cancer and other diseases. Micro-crystalline cellulose in particular is among the most frequently used cellulose derivatives in the food, cosmetics, pharma industry, etc. and is an important excipient due to its binding and tableting properties, characterized by its plasticity and cohesiveness when wet. Bacterial cellulose's high dispensability, tasteless and odourless nature provides it with lot of industrial applications. Currently, about half of the waste produced in India contains about 50% cellulose which can be used productively. This chapter deals with the chemistry of cellulose, its extraction and its properties which help various industries to make the most of it.
    { "chemical": "['Cellulose', 'organic polymers', 'polysaccharide', 'celluloses', 'cellulose derivatives', 'cellulose', 'cellulose']" }

    TEXT: 3.4. Ionic Cross-Linking. The strength of the macrofibers is considerably susceptible to the slide and void between nanofibers. Especially in high moisture, weakening of the interfacial linkage between nanofibers may lead to an obvious decrease in mechanical properties. Organic carboxylic sodium salt is a weak polyelectrolyte, so the internal cohesion should be improved by incorporation of ionic bonds. In the pursuit of high-performance nanostructure materials, previous reports and theoretical investigations proposed that multivalent ions offered cross-linking bridges between the oxygen-containing groups and thus achieved the enhancement of mechanical properties in high humidity. We chose CuSO <sub>4</sub> and Fe <sub>2</sub> (SO <sub>4</sub> ) <sub>3</sub> as the bath solutions and immersed drawn fibers (SR = 0.2) into them for 24 h, respectively, followed by extensive washing. The obtained fibers show the typical colors of the metal ions; that is, the fibers immersed with CuSO <sub>4</sub> are blue, and those immersed with Fe <sub>2</sub> (SO <sub>4</sub> ) <sub>3</sub> are yellow. The composition was analyzed by elemental analysis via ICP-AES. The results show that the sodium content is reduced from 2.43 to 0.01 and 0.18 wt % for the Cu <super>2+</super> and Fe <super>3+</super> infiltrated fibers. Cu <super>2+</super> and Fe <super>3+</super> can be detected in fibers with 2.83 and 2.48 wt %, respectively. This indicates the majority of the Na <super>+</super> was exchanged by Cu <super>2+</super> or Fe <super>3+</super> .
    { "chemical": "['Organic carboxylic sodium salt', 'CuSO <sub>4</sub>', 'Fe <sub>2</sub> (SO <sub>4</sub> ) <sub>3</sub>', 'CuSO <sub>4</sub>', 'Fe <sub>2</sub> (SO <sub>4</sub> ) <sub>3</sub>', 'sodium']" }
    
    TEXT: The lower orientation of the cellulose microfibrils in cotton fibers (helix angle ≈18°) gives rise to a smaller module of elasticity and a higher elongation at breakage compared with bast fibers, which have a much higher microfibril orientation (helix angle ≈4°-5°) and fiber strength. The adaptation of the mechanical properties of wood to environmental conditions through corresponding helix angles is fascinating, and has yet to be rivaled in technical composite materials. However, it is already possible to adapt the parameters of cellulosic man-made fibers to user requirements through a targeted influence on the orientation (with particular respect to the noncrystalline chain segments). It is therefore possible to develop man-made cellulose fibers similar to cotton with low orientation (high elongation), and technical fibers with high orientation and a high modulus of elasticity, similar to bast fibers.
    { "chemical": "[]" }
    """,
    """
    TEXT: As a result of the extended hydrogen bonds between the cellulose chains, special media and procedures must be applied to dissolve cellulose. Today, solvents are divided into derivatizing solvents (forming covalent bonds of low stability with the polymer) and nonderivatizing solvents (interacting only physically with the polymer). At the industrial scale, cellulose nitrate as a soluble and, thus, formable cellulose derivative can be used. It should be pointed out that cellulose nitrate is a relatively stable cellulose derivative so introduction of ester moieties for "derivatizing dissolution" is somewhat questionable, although regeneration is easy to achieve. The invention of a mixture of copper(II) hydroxide and aqueous ammonia for dissolving cellulose, with subsequent precipitation in dilute sulfuric acid, was followed by probably the most important large-scale technical process in fiber production, the viscose process. Cellulose is transformed into cellulose xanthogenate, with subsequent spinning of the solution in aqueous sodium hydroxide. The Lyocell process is an environmentally friendly alternative to the viscose process, whereby cellulose is dissolved physically in N-methylmorpholine-N-oxide monohydrate and regenerated in water.
    { "material": "['media', 'cellulose', 'polymer', 'formable cellulose derivative', 'cellulose', 'cellulose', 'water']" }

    TEXT: The lower orientation of the cellulose microfibrils in cotton fibers (helix angle ≈18°) gives rise to a smaller module of elasticity and a higher elongation at breakage compared with bast fibers, which have a much higher microfibril orientation (helix angle ≈4°-5°) and fiber strength. The adaptation of the mechanical properties of wood to environmental conditions through corresponding helix angles is fascinating, and has yet to be rivaled in technical composite materials. However, it is already possible to adapt the parameters of cellulosic man-made fibers to user requirements through a targeted influence on the orientation (with particular respect to the noncrystalline chain segments). It is therefore possible to develop man-made cellulose fibers similar to cotton with low orientation (high elongation), and technical fibers with high orientation and a high modulus of elasticity, similar to bast fibers.
    { "material": "['cotton fibers', 'bast fibers', 'wood', 'composite materials', 'cotton']" }
    
    TEXT: All cell walls contain two layers, the middle lamella and the primary cell wall, and many cells produce an additional layer, called the secondary wall. The middle lamella serves as a cementing layer between the primary walls of adjacent cells. The primary wall is the cellulose-containing layer laid down by cells that are dividing and growing. To allow for cell wall expansion during growth, primary walls are thinner and less rigid than those of cells that have stopped growing. A fully grown plant cell may retain its primary cell wall (sometimes thickening it), or it may deposit an additional, rigidifying layer of different composition, which is the secondary cell wall.
    { "material": "[]" }
    """,
    """
    TEXT: The lower orientation of the cellulose microfibrils in cotton fibers (helix angle ≈18°) gives rise to a smaller module of elasticity and a higher elongation at breakage compared with bast fibers, which have a much higher microfibril orientation (helix angle ≈4°-5°) and fiber strength. The adaptation of the mechanical properties of wood to environmental conditions through corresponding helix angles is fascinating, and has yet to be rivaled in technical composite materials. However, it is already possible to adapt the parameters of cellulosic man-made fibers to user requirements through a targeted influence on the orientation (with particular respect to the noncrystalline chain segments). It is therefore possible to develop man-made cellulose fibers similar to cotton with low orientation (high elongation), and technical fibers with high orientation and a high modulus of elasticity, similar to bast fibers.
    { "structure": "['cellulose microfibrils', 'cellulosic man-made fibers', 'noncrystalline chain', 'man-made cellulose fibers', 'technical fibers', 'bast fibers']" }

    TEXT: Regioselectively substituted (position 2, 3 or 6 of the AGU) cellulose phenylurethanes with F, Cl, or CH <sub>3</sub> groups in the phenyl ring form lyotropic liquid-crystalline mesophases in highly concentrated solutions, the structure and optical properties of which depend strongly on the site of substitution, as well as on the concentration and temperature of the solution. The photo-cross-linking of cellulose-(3-chlorophenyl)-urethanes in mixtures with acrylate monomers produces semi-interpenetrating polymer networks, which can change their selective reflection under compression. Cellulose urethanes with azo-dye substituents and acrylates of hydroxypropyl cellulose are other well-analyzed lyotropic liquid-crystalline cellulose products. The latter form gels in water through photo-cross-linking, and their resulting color is determined by the water content. The optical properties that can be controlled by the pitch of cholesteric phases open up important fields of application, such as color pigments in car paints and as copy protection color for document papers.
    { "structure": "['F, Cl, or CH <sub>3</sub> groups', 'phenyl ring', 'acrylate monomers', 'polymer networks']" }
    
    TEXT: The first ionic liquids (ILs) used for esterification of cellulose were Nalkylpyridinium halides, especially N-ethylpyridinium chloride (EPyCl) and N-benzylpyridinium chloride (BPyCl). Nevertheless, the most promising ILs for the modification of cellulose are the salts of 1-alkyl-3-methylimidazolium. In 2002, it was shown that such ILs could open new paths for the shaping of polysaccharides. Additionally, they could lead to commercially relevant routes toward homogeneous cellulose chemistry, which would significantly broaden the number of tailored cellulose derivatives. Meanwhile, a huge number of cellulose-dissolving ILs are now known and discussed in various recent reviews (e.g., and references cited therein), and the number of reported low melting organic salts is growing rapidly (Fig. 22). Nevertheless, according to the literature and our own experience, cellulose can be dissolved in ILs with imidazolium, ammonium, and pyridinium. Only organic salts with asymmetric cations give melts that can interact with the backbone of cellulose. Neither sulfonium nor phosphonium salts have so far been able to dissolve cellulose. Dissolution of cellulose in pyridinium salts must be performed under protective gas otherwise degradation results.
    { "structure": "[]" }
    """,
    """
    TEXT: From the advent of novel drug delivery systems, cellulose based models seemed like strong candidates due to their projected benefits. Since then various advances have been made with the aim to bring its use to common practice. There are still many hurdles to cross before this becomes a reality. Cellulose based drug delivery is an important step in green and sustainable pharmacy which focuses on toxicity reduction, biodegradability and less hazardous synthesis with respect to drugs and drug delivery systems. A very brief overview of the primary ways in which it is used is provided here. Cellulose nanocrystals (CNCs) have the potential to acquire a negative charge during hydrolysis. This coupled with their large surface area allow them to bind ionizable drugs such as tetracycline and doxorubicin permitting optimum dosing control. Sites for surface modification for multiple chemicals are provided by the multitude of surface hydroxyl groups. This is used in case of non-ionized or hydrophobic drugs which do not generally bind to cellulose. The open pore structure and high surface area of CNC based aerogels provide increased drug loading capacity and drug bioavailability. Extremely porous aerogel scaffolds were reported to attain sustained drug release.
    { "property": "['sustainable', 'negative charge', 'large surface area', 'ionizable', 'non-ionized', 'hydrophobic', 'high surface area', 'drug loading capacity', 'drug bioavailability', 'Extremely porous']" }
    
    TEXT: Cellulose derivatives have also been researched in terms of drug delivery. For instance, cellulose acetate has been successfully used in several HIV drugs, five flavonoids, one pain reliever and two antibiotics among others. Hydroxypropyl methylcellulose has been used in oral drug delivery formulations.
    { "property": "[]" }
    """,
    """
    TEXT: Cellulose (C <sub>6</sub> H <sub>10</sub> O <sub>5</sub> ) <sub>n</sub> is one of the most ubiquitous organic polymers on the planet. It is a significant structural component of the primary cell wall of green plants, various forms of algae and oomycetes. It is a polysaccharide consisting of a linear chain of several hundred to many thousands of β(1 → 4) linked d-glucose units. There are various extraction procedures for cellulose developed by using different processes like oxidation, etherification and esterification which convert the prepared celluloses in to cellulose derivatives. Since it is a non-toxic, bio-degradable polymer with high tensile and compressive strength, it has widespread use in various fields such as nanotechnology, pharmaceutical industry, food industry, cosmetics, textile and paper industry, drug-delivery systems in treating cancer and other diseases. Micro-crystalline cellulose in particular is among the most frequently used cellulose derivatives in the food, cosmetics, pharma industry, etc. and is an important excipient due to its binding and tableting properties, characterized by its plasticity and cohesiveness when wet. Bacterial cellulose's high dispensability, tasteless and odourless nature provides it with lot of industrial applications. Currently, about half of the waste produced in India contains about 50% cellulose which can be used productively. This chapter deals with the chemistry of cellulose, its extraction and its properties which help various industries to make the most of it.
    { "application": "['cosmetics', 'textile', 'paper', 'drug-delivery', 'food', 'cosmetics']" }

    TEXT: The structure of cellulose has been constantly a subject requiring intensive research as it is formed by the hydrogen bonds between the network of hydroxy groups. The progress was for more than a 100 years of intensive development on structure analysis methods like electron microscopy, X-ray diffraction and high resolution solid state NMR spectroscopy. The complete detailed analysis is required for the procedures of synthetic reactions and cellulose based manmade products with extensive applications. The structure of cellulose as depicted in Figure 2 consists of hydroxyl groups of β-1,4-glucan cellulose at C2, C3 and C6. The CH <sub>2</sub> OH group is positioned relative to the C4 and C5 bonds along with a shear relativity with O5–C5 bonds. The solid state is equally likely to be represented in the crystalline (high order) and amorphous (low order). The crystal structure in particular is determined by the X-ray diffraction using a monoclinic unit cell which is made up of two cellulose chains in a parallel orientation and two fold screw axis. The investigations with respect to the electron microbeam diffraction, combined X-ray and neutron diffraction have clearly indicated that the cellulose crystalline structures have a triclinic and monoclinic unit cell. The schematic representations of the I <sub>β</sub> crystal structure, in Figure 3, indicate the two intramolecular chain-stiffening hydrogen bonds. The recent researches on the I <sub>β</sub> crystal structure have different H-bonds and different conformations of neighbouring chains. The thermodynamically stable cellulose II can occur in other forms of crystal structures and is the most stable form of cellulose. The cellulose I can be treated with aqueous sodium hydroxide to form cellulose II.
    { "application": "['cellulose based manmade products']" }

    TEXT: From the advent of novel drug delivery systems, cellulose based models seemed like strong candidates due to their projected benefits. Since then various advances have been made with the aim to bring its use to common practice. There are still many hurdles to cross before this becomes a reality. Cellulose based drug delivery is an important step in green and sustainable pharmacy which focuses on toxicity reduction, biodegradability and less hazardous synthesis with respect to drugs and drug delivery systems. A very brief overview of the primary ways in which it is used is provided here. Cellulose nanocrystals (CNCs) have the potential to acquire a negative charge during hydrolysis. This coupled with their large surface area allow them to bind ionizable drugs such as tetracycline and doxorubicin permitting optimum dosing control. Sites for surface modification for multiple chemicals are provided by the multitude of surface hydroxyl groups. This is used in case of non-ionized or hydrophobic drugs which do not generally bind to cellulose. The open pore structure and high surface area of CNC based aerogels provide increased drug loading capacity and drug bioavailability. Extremely porous aerogel scaffolds were reported to attain sustained drug release.
    { "application": "['aerogel scaffolds', 'drug release']" }

    TEXT: Regioselectively substituted (position 2, 3 or 6 of the AGU) cellulose phenylurethanes with F, Cl, or CH <sub>3</sub> groups in the phenyl ring form lyotropic liquid-crystalline mesophases in highly concentrated solutions, the structure and optical properties of which depend strongly on the site of substitution, as well as on the concentration and temperature of the solution. The photo-cross-linking of cellulose-(3-chlorophenyl)-urethanes in mixtures with acrylate monomers produces semi-interpenetrating polymer networks, which can change their selective reflection under compression. Cellulose urethanes with azo-dye substituents and acrylates of hydroxypropyl cellulose are other well-analyzed lyotropic liquid-crystalline cellulose products. The latter form gels in water through photo-cross-linking, and their resulting color is determined by the water content. The optical properties that can be controlled by the pitch of cholesteric phases open up important fields of application, such as color pigments in car paints and as copy protection color for document papers.
    { "application": "['car paints', 'document papers']" }
    
    TEXT: Cellulose II (see Sect. 3.3) shows a different hydrogen bonding system. Because of the existence of an intermolecular hydrogen bond between the OH groups of C6 and C2 of another chain, the intramolecular bonding of OH in C2 is avoided and an intermolecular hydrogen bond of OH-C2 to OH-C2 of the next chain is formed. In comparison to cellulose I, the cellulose II molecules are more densely packed and strongly interbonded and, therefore, cellulose II is less reactive, as commonly observed. Figure 3 shows a scheme of the hydrogen bonding system in cellulose I and II.
    { "application": "[]" }
    """,
    """
    TEXT: Celluloses from different sources possess comparable crystallinity (i.e., modifications of cellulose I). However, solid state <super>13</super> C-NMR studies revealed that cellulose can crystallize with varying proportions of two different phases, named cellulose I <sub>α</sub> and I <sub>β</sub> . Plant cellulose mainly consists of cellulose I <sub>β</sub> , whereas cellulose produced by primitive organisms crystallizes in the I <sub>α</sub> phase. The monoclinic unit cell of cellulose I <sub>α</sub> with a space group P2 <sub>1</sub> consists of two cellulose molecules, each containing a cellobiose unit in the 002 corner plane and 002 center plane in a parallel fashion. Cellulose I <sub>β</sub> corresponds to a triclinic symmetry with space group P <sub>1</sub> containing one chain in the unit cell, as schematically displayed in Fig. 6a.
    { "process": "['modifications of cellulose I', 'solid state <super>13</super> C-NMR', 'crystallize', 'crystallizes']" }

    TEXT: As a result of the extended hydrogen bonds between the cellulose chains, special media and procedures must be applied to dissolve cellulose. Today, solvents are divided into derivatizing solvents (forming covalent bonds of low stability with the polymer) and nonderivatizing solvents (interacting only physically with the polymer). At the industrial scale, cellulose nitrate as a soluble and, thus, formable cellulose derivative can be used. It should be pointed out that cellulose nitrate is a relatively stable cellulose derivative so introduction of ester moieties for "derivatizing dissolution" is somewhat questionable, although regeneration is easy to achieve. The invention of a mixture of copper(II) hydroxide and aqueous ammonia for dissolving cellulose, with subsequent precipitation in dilute sulfuric acid, was followed by probably the most important large-scale technical process in fiber production, the viscose process. Cellulose is transformed into cellulose xanthogenate, with subsequent spinning of the solution in aqueous sodium hydroxide. The Lyocell process is an environmentally friendly alternative to the viscose process, whereby cellulose is dissolved physically in N-methylmorpholine-N-oxide monohydrate and regenerated in water.
    { "process": "['procedures', 'derivatizing dissolution', 'regeneration', 'fiber production', 'viscose process', 'spinning', 'Lyocell process', 'viscose process']" }
    
    TEXT: Figure 1 shows the molecular structure of cellulose as a carbohydrate polymer generated from repeating b-d-glucopyranose molecules that are covalently linked through acetal functions between the equatorial OH group of C4 and the C1 carbon atom (b-1,4-glucan), which is, in principle, the manner in which cellulose is biogenetically formed. As a result, cellulose is an extensive, linear-chain polymer with a large number of hydroxy groups (three per anhydroglucose (AGU) unit) present in the thermodynamically preferred <super>4</super> C <sub>1</sub> conformation. To accommodate the preferred bond angles of the acetal oxygen bridges, every second AGU ring is rotated 1808 in the plane. In this manner, two adjacent structural units define the disaccharide cellobiose.
    { "process": "[]" }
    """,
]

example_20 = [
    """
    TEXT: Cellulose (C <sub>6</sub> H <sub>10</sub> O <sub>5</sub> ) <sub>n</sub> is one of the most ubiquitous organic polymers on the planet. It is a significant structural component of the primary cell wall of green plants, various forms of algae and oomycetes. It is a polysaccharide consisting of a linear chain of several hundred to many thousands of β(1 → 4) linked d-glucose units. There are various extraction procedures for cellulose developed by using different processes like oxidation, etherification and esterification which convert the prepared celluloses in to cellulose derivatives. Since it is a non-toxic, bio-degradable polymer with high tensile and compressive strength, it has widespread use in various fields such as nanotechnology, pharmaceutical industry, food industry, cosmetics, textile and paper industry, drug-delivery systems in treating cancer and other diseases. Micro-crystalline cellulose in particular is among the most frequently used cellulose derivatives in the food, cosmetics, pharma industry, etc. and is an important excipient due to its binding and tableting properties, characterized by its plasticity and cohesiveness when wet. Bacterial cellulose's high dispensability, tasteless and odourless nature provides it with lot of industrial applications. Currently, about half of the waste produced in India contains about 50% cellulose which can be used productively. This chapter deals with the chemistry of cellulose, its extraction and its properties which help various industries to make the most of it.
    { "chemical": "['Cellulose', 'organic polymers', 'polysaccharide', 'celluloses', 'cellulose derivatives', 'cellulose', 'cellulose']" }

    TEXT: As a result of the extended hydrogen bonds between the cellulose chains, special media and procedures must be applied to dissolve cellulose. Today, solvents are divided into derivatizing solvents (forming covalent bonds of low stability with the polymer) and nonderivatizing solvents (interacting only physically with the polymer). At the industrial scale, cellulose nitrate as a soluble and, thus, formable cellulose derivative can be used. It should be pointed out that cellulose nitrate is a relatively stable cellulose derivative so introduction of ester moieties for "derivatizing dissolution" is somewhat questionable, although regeneration is easy to achieve. The invention of a mixture of copper(II) hydroxide and aqueous ammonia for dissolving cellulose, with subsequent precipitation in dilute sulfuric acid, was followed by probably the most important large-scale technical process in fiber production, the viscose process. Cellulose is transformed into cellulose xanthogenate, with subsequent spinning of the solution in aqueous sodium hydroxide. The Lyocell process is an environmentally friendly alternative to the viscose process, whereby cellulose is dissolved physically in N-methylmorpholine-N-oxide monohydrate and regenerated in water.
    { "chemical": "['polymer', 'cellulose nitrate', 'cellulose nitrate', 'cellulose derivative', 'copper(II) hydroxide', 'ammonia', 'sulfuric acid', 'Cellulose', 'cellulose xanthogenate', 'sodium hydroxide', 'N-methylmorpholine-N-oxide monohydrate']" }

    TEXT: The microstructure of CNC particles depends strongly on the drying method employed during manufacturing. The effect of different drying techniques, including spray drying, freeze drying, and spray freeze drying (SFD), on microstructure of cellulose nanocrystal (CNC) particles was studied. Conventional drying methods (i.e. spray and freeze drying) yielded packed and dense agglomerates of CNC. Capillary forces and ice crystal growth play key roles in CNC aggregation during spray and freeze drying, respectively. It was found that, in the absence of these forces, in the SFD technique, the dispersed state of CNC in water could be frozen in. Thus, SFD of CNC suspension resulted in a powder with porous structure. A filament-like agglomerate structure consisting of nanofibers was formed at low CNC concentrations (ca. <2 wt.%), while a spherical foam structure was obtained at higher CNC concentrations. Polypropylene (PP) nanocomposites containing spray dried CNC, freeze dried CNC, and spray freeze dried CNC (CNCSFD) were prepared via melt mixing in an internal batch mixer. Optical light and scanning electron microscopy coupled with rheological properties showed better dispersion of CNCSFD agglomerates. Moreover, PP samples containing CNCSFD showed significant increases in mechanical properties.
    { "chemical": "['Polypropylene']" }

    TEXT: 3.4. Ionic Cross-Linking. The strength of the macrofibers is considerably susceptible to the slide and void between nanofibers. Especially in high moisture, weakening of the interfacial linkage between nanofibers may lead to an obvious decrease in mechanical properties. Organic carboxylic sodium salt is a weak polyelectrolyte, so the internal cohesion should be improved by incorporation of ionic bonds. In the pursuit of high-performance nanostructure materials, previous reports and theoretical investigations proposed that multivalent ions offered cross-linking bridges between the oxygen-containing groups and thus achieved the enhancement of mechanical properties in high humidity. We chose CuSO <sub>4</sub> and Fe <sub>2</sub> (SO <sub>4</sub> ) <sub>3</sub> as the bath solutions and immersed drawn fibers (SR = 0.2) into them for 24 h, respectively, followed by extensive washing. The obtained fibers show the typical colors of the metal ions; that is, the fibers immersed with CuSO <sub>4</sub> are blue, and those immersed with Fe <sub>2</sub> (SO <sub>4</sub> ) <sub>3</sub> are yellow. The composition was analyzed by elemental analysis via ICP-AES. The results show that the sodium content is reduced from 2.43 to 0.01 and 0.18 wt % for the Cu <super>2+</super> and Fe <super>3+</super> infiltrated fibers. Cu <super>2+</super> and Fe <super>3+</super> can be detected in fibers with 2.83 and 2.48 wt %, respectively. This indicates the majority of the Na <super>+</super> was exchanged by Cu <super>2+</super> or Fe <super>3+</super> .
    { "chemical": "['Organic carboxylic sodium salt', 'CuSO <sub>4</sub>', 'Fe <sub>2</sub> (SO <sub>4</sub> ) <sub>3</sub>', 'CuSO <sub>4</sub>', 'Fe <sub>2</sub> (SO <sub>4</sub> ) <sub>3</sub>', 'sodium']" }
    
    TEXT: The lower orientation of the cellulose microfibrils in cotton fibers (helix angle ≈18°) gives rise to a smaller module of elasticity and a higher elongation at breakage compared with bast fibers, which have a much higher microfibril orientation (helix angle ≈4°-5°) and fiber strength. The adaptation of the mechanical properties of wood to environmental conditions through corresponding helix angles is fascinating, and has yet to be rivaled in technical composite materials. However, it is already possible to adapt the parameters of cellulosic man-made fibers to user requirements through a targeted influence on the orientation (with particular respect to the noncrystalline chain segments). It is therefore possible to develop man-made cellulose fibers similar to cotton with low orientation (high elongation), and technical fibers with high orientation and a high modulus of elasticity, similar to bast fibers.
    { "chemical": "[]" }
    """,
    """
    TEXT: As a result of the extended hydrogen bonds between the cellulose chains, special media and procedures must be applied to dissolve cellulose. Today, solvents are divided into derivatizing solvents (forming covalent bonds of low stability with the polymer) and nonderivatizing solvents (interacting only physically with the polymer). At the industrial scale, cellulose nitrate as a soluble and, thus, formable cellulose derivative can be used. It should be pointed out that cellulose nitrate is a relatively stable cellulose derivative so introduction of ester moieties for "derivatizing dissolution" is somewhat questionable, although regeneration is easy to achieve. The invention of a mixture of copper(II) hydroxide and aqueous ammonia for dissolving cellulose, with subsequent precipitation in dilute sulfuric acid, was followed by probably the most important large-scale technical process in fiber production, the viscose process. Cellulose is transformed into cellulose xanthogenate, with subsequent spinning of the solution in aqueous sodium hydroxide. The Lyocell process is an environmentally friendly alternative to the viscose process, whereby cellulose is dissolved physically in N-methylmorpholine-N-oxide monohydrate and regenerated in water.
    { "material": "['media', 'cellulose', 'polymer', 'formable cellulose derivative', 'cellulose', 'cellulose', 'water']" }

    TEXT: The lower orientation of the cellulose microfibrils in cotton fibers (helix angle ≈18°) gives rise to a smaller module of elasticity and a higher elongation at breakage compared with bast fibers, which have a much higher microfibril orientation (helix angle ≈4°-5°) and fiber strength. The adaptation of the mechanical properties of wood to environmental conditions through corresponding helix angles is fascinating, and has yet to be rivaled in technical composite materials. However, it is already possible to adapt the parameters of cellulosic man-made fibers to user requirements through a targeted influence on the orientation (with particular respect to the noncrystalline chain segments). It is therefore possible to develop man-made cellulose fibers similar to cotton with low orientation (high elongation), and technical fibers with high orientation and a high modulus of elasticity, similar to bast fibers.
    { "material": "['cotton fibers', 'bast fibers', 'wood', 'composite materials', 'cotton']" }

    TEXT: The microstructure of CNC particles depends strongly on the drying method employed during manufacturing. The effect of different drying techniques, including spray drying, freeze drying, and spray freeze drying (SFD), on microstructure of cellulose nanocrystal (CNC) particles was studied. Conventional drying methods (i.e. spray and freeze drying) yielded packed and dense agglomerates of CNC. Capillary forces and ice crystal growth play key roles in CNC aggregation during spray and freeze drying, respectively. It was found that, in the absence of these forces, in the SFD technique, the dispersed state of CNC in water could be frozen in. Thus, SFD of CNC suspension resulted in a powder with porous structure. A filament-like agglomerate structure consisting of nanofibers was formed at low CNC concentrations (ca. <2 wt.%), while a spherical foam structure was obtained at higher CNC concentrations. Polypropylene (PP) nanocomposites containing spray dried CNC, freeze dried CNC, and spray freeze dried CNC (CNCSFD) were prepared via melt mixing in an internal batch mixer. Optical light and scanning electron microscopy coupled with rheological properties showed better dispersion of CNCSFD agglomerates. Moreover, PP samples containing CNCSFD showed significant increases in mechanical properties.
    { "material": "['CNC particles', 'particles', 'water', 'CNC suspension', 'powder', 'nanocomposites', 'CNCSFD agglomerates', 'PP samples containing CNCSFD']" }

    TEXT: Bacterial cellulose (BC) nanofibers represent an emerging class of highly crystalline bionanofibers with high intrinsic mechanical properties. The remarkable nanofibers with oriented structure and strong interfibrillar interactions can realize high performance materials. In this study, we demonstrated that macrofibers based on aligned BC nanofibers could be prepared by wet spinning and drawing procedures. The relationship between process conditions, structure, and mechanical properties of macrofibers were investigated. The obtained macrofibers exhibited Young's modulus of 16.4 GPa and tensile strength of 248.6 MPa under the optimum process conditions, in which nanofibers displayed a high degree of alignment. Furthermore, we enhanced the interfacial interactions between nanofibers and obtained better mechanical performance by multivalent ion cross-linking. After exchanging the monovalent Na <super>+</super> by Fe <super>3+</super> , the dried macrofiber reached Young's modulus of 22.9 GPa and tensile strength of 357.5 MPa. Particularly, the resulting macrofibers still maintained good mechanical properties with Young's modulus of 15.9 GPa and tensile strength of 262.2 MPa in the wet condition. This research provided a good method to fabricate macrofibers from BC nanofibers with good properties by continuous wet-spinning process. These macrofibers can be easily functionalized and have promising potential applications in smart textiles, biosensor, and structural reinforcement.
    { "material": "['Bacterial cellulose']" }

    TEXT: 3.4. Ionic Cross-Linking. The strength of the macrofibers is considerably susceptible to the slide and void between nanofibers. Especially in high moisture, weakening of the interfacial linkage between nanofibers may lead to an obvious decrease in mechanical properties. Organic carboxylic sodium salt is a weak polyelectrolyte, so the internal cohesion should be improved by incorporation of ionic bonds. In the pursuit of high-performance nanostructure materials, previous reports and theoretical investigations proposed that multivalent ions offered cross-linking bridges between the oxygen-containing groups and thus achieved the enhancement of mechanical properties in high humidity. We chose CuSO <sub>4</sub> and Fe <sub>2</sub> (SO <sub>4</sub> ) <sub>3</sub> as the bath solutions and immersed drawn fibers (SR = 0.2) into them for 24 h, respectively, followed by extensive washing. The obtained fibers show the typical colors of the metal ions; that is, the fibers immersed with CuSO <sub>4</sub> are blue, and those immersed with Fe <sub>2</sub> (SO <sub>4</sub> ) <sub>3</sub> are yellow. The composition was analyzed by elemental analysis via ICP-AES. The results show that the sodium content is reduced from 2.43 to 0.01 and 0.18 wt % for the Cu <super>2+</super> and Fe <super>3+</super> infiltrated fibers. Cu <super>2+</super> and Fe <super>3+</super> can be detected in fibers with 2.83 and 2.48 wt %, respectively. This indicates the majority of the Na <super>+</super> was exchanged by Cu <super>2+</super> or Fe <super>3+</super> .
    { "material": "['polyelectrolyte', 'nanostructure materials']" }
    
    TEXT: All cell walls contain two layers, the middle lamella and the primary cell wall, and many cells produce an additional layer, called the secondary wall. The middle lamella serves as a cementing layer between the primary walls of adjacent cells. The primary wall is the cellulose-containing layer laid down by cells that are dividing and growing. To allow for cell wall expansion during growth, primary walls are thinner and less rigid than those of cells that have stopped growing. A fully grown plant cell may retain its primary cell wall (sometimes thickening it), or it may deposit an additional, rigidifying layer of different composition, which is the secondary cell wall.
    { "material": "[]" }
    """,
    """
    TEXT: Cellulose II (see Sect. 3.3) shows a different hydrogen bonding system. Because of the existence of an intermolecular hydrogen bond between the OH groups of C6 and C2 of another chain, the intramolecular bonding of OH in C2 is avoided and an intermolecular hydrogen bond of OH-C2 to OH-C2 of the next chain is formed. In comparison to cellulose I, the cellulose II molecules are more densely packed and strongly interbonded and, therefore, cellulose II is less reactive, as commonly observed. Figure 3 shows a scheme of the hydrogen bonding system in cellulose I and II.
    { "structure": "['Cellulose II', 'intermolecular hydrogen bond', 'OH groups', 'C6', 'C2', 'OH', 'C2', 'intermolecular hydrogen bond', 'OH-C2', 'OH-C2', 'cellulose I', 'cellulose II', 'cellulose I and II']" }

    TEXT: The lower orientation of the cellulose microfibrils in cotton fibers (helix angle ≈18°) gives rise to a smaller module of elasticity and a higher elongation at breakage compared with bast fibers, which have a much higher microfibril orientation (helix angle ≈4°-5°) and fiber strength. The adaptation of the mechanical properties of wood to environmental conditions through corresponding helix angles is fascinating, and has yet to be rivaled in technical composite materials. However, it is already possible to adapt the parameters of cellulosic man-made fibers to user requirements through a targeted influence on the orientation (with particular respect to the noncrystalline chain segments). It is therefore possible to develop man-made cellulose fibers similar to cotton with low orientation (high elongation), and technical fibers with high orientation and a high modulus of elasticity, similar to bast fibers.
    { "structure": "['cellulose microfibrils', 'cellulosic man-made fibers', 'noncrystalline chain', 'man-made cellulose fibers', 'technical fibers', 'bast fibers']" }

    TEXT: Regioselectively substituted (position 2, 3 or 6 of the AGU) cellulose phenylurethanes with F, Cl, or CH <sub>3</sub> groups in the phenyl ring form lyotropic liquid-crystalline mesophases in highly concentrated solutions, the structure and optical properties of which depend strongly on the site of substitution, as well as on the concentration and temperature of the solution. The photo-cross-linking of cellulose-(3-chlorophenyl)-urethanes in mixtures with acrylate monomers produces semi-interpenetrating polymer networks, which can change their selective reflection under compression. Cellulose urethanes with azo-dye substituents and acrylates of hydroxypropyl cellulose are other well-analyzed lyotropic liquid-crystalline cellulose products. The latter form gels in water through photo-cross-linking, and their resulting color is determined by the water content. The optical properties that can be controlled by the pitch of cholesteric phases open up important fields of application, such as color pigments in car paints and as copy protection color for document papers.
    { "structure": "['F, Cl, or CH <sub>3</sub> groups', 'phenyl ring', 'acrylate monomers', 'polymer networks']" }
    
    TEXT: The first ionic liquids (ILs) used for esterification of cellulose were Nalkylpyridinium halides, especially N-ethylpyridinium chloride (EPyCl) and N-benzylpyridinium chloride (BPyCl). Nevertheless, the most promising ILs for the modification of cellulose are the salts of 1-alkyl-3-methylimidazolium. In 2002, it was shown that such ILs could open new paths for the shaping of polysaccharides. Additionally, they could lead to commercially relevant routes toward homogeneous cellulose chemistry, which would significantly broaden the number of tailored cellulose derivatives. Meanwhile, a huge number of cellulose-dissolving ILs are now known and discussed in various recent reviews (e.g., and references cited therein), and the number of reported low melting organic salts is growing rapidly (Fig. 22). Nevertheless, according to the literature and our own experience, cellulose can be dissolved in ILs with imidazolium, ammonium, and pyridinium. Only organic salts with asymmetric cations give melts that can interact with the backbone of cellulose. Neither sulfonium nor phosphonium salts have so far been able to dissolve cellulose. Dissolution of cellulose in pyridinium salts must be performed under protective gas otherwise degradation results.
    { "structure": "[]" }
    """,
    """
    TEXT: The structure of cellulose has been constantly a subject requiring intensive research as it is formed by the hydrogen bonds between the network of hydroxy groups. The progress was for more than a 100 years of intensive development on structure analysis methods like electron microscopy, X-ray diffraction and high resolution solid state NMR spectroscopy. The complete detailed analysis is required for the procedures of synthetic reactions and cellulose based manmade products with extensive applications. The structure of cellulose as depicted in Figure 2 consists of hydroxyl groups of β-1,4-glucan cellulose at C2, C3 and C6. The CH <sub>2</sub> OH group is positioned relative to the C4 and C5 bonds along with a shear relativity with O5–C5 bonds. The solid state is equally likely to be represented in the crystalline (high order) and amorphous (low order). The crystal structure in particular is determined by the X-ray diffraction using a monoclinic unit cell which is made up of two cellulose chains in a parallel orientation and two fold screw axis. The investigations with respect to the electron microbeam diffraction, combined X-ray and neutron diffraction have clearly indicated that the cellulose crystalline structures have a triclinic and monoclinic unit cell. The schematic representations of the I <sub>β</sub> crystal structure, in Figure 3, indicate the two intramolecular chain-stiffening hydrogen bonds. The recent researches on the I <sub>β</sub> crystal structure have different H-bonds and different conformations of neighbouring chains. The thermodynamically stable cellulose II can occur in other forms of crystal structures and is the most stable form of cellulose. The cellulose I can be treated with aqueous sodium hydroxide to form cellulose II.
    { "property": "['crystalline', 'amorphous', 'triclinic', 'monoclinic', 'different conformations', 'thermodynamically stable', 'most stable']" }

    TEXT: From the advent of novel drug delivery systems, cellulose based models seemed like strong candidates due to their projected benefits. Since then various advances have been made with the aim to bring its use to common practice. There are still many hurdles to cross before this becomes a reality. Cellulose based drug delivery is an important step in green and sustainable pharmacy which focuses on toxicity reduction, biodegradability and less hazardous synthesis with respect to drugs and drug delivery systems. A very brief overview of the primary ways in which it is used is provided here. Cellulose nanocrystals (CNCs) have the potential to acquire a negative charge during hydrolysis. This coupled with their large surface area allow them to bind ionizable drugs such as tetracycline and doxorubicin permitting optimum dosing control. Sites for surface modification for multiple chemicals are provided by the multitude of surface hydroxyl groups. This is used in case of non-ionized or hydrophobic drugs which do not generally bind to cellulose. The open pore structure and high surface area of CNC based aerogels provide increased drug loading capacity and drug bioavailability. Extremely porous aerogel scaffolds were reported to attain sustained drug release.
    { "property": "['sustainable', 'negative charge', 'large surface area', 'ionizable', 'non-ionized', 'hydrophobic', 'high surface area', 'drug loading capacity', 'drug bioavailability', 'Extremely porous']" }

    TEXT: Cellulose II (see Sect. 3.3) shows a different hydrogen bonding system. Because of the existence of an intermolecular hydrogen bond between the OH groups of C6 and C2 of another chain, the intramolecular bonding of OH in C2 is avoided and an intermolecular hydrogen bond of OH-C2 to OH-C2 of the next chain is formed. In comparison to cellulose I, the cellulose II molecules are more densely packed and strongly interbonded and, therefore, cellulose II is less reactive, as commonly observed. Figure 3 shows a scheme of the hydrogen bonding system in cellulose I and II.
    { "property": "['densely packed', 'strongly interbonded', 'less reactive']" }
    
    TEXT: Cellulose derivatives have also been researched in terms of drug delivery. For instance, cellulose acetate has been successfully used in several HIV drugs, five flavonoids, one pain reliever and two antibiotics among others. Hydroxypropyl methylcellulose has been used in oral drug delivery formulations.
    { "property": "[]" }
    """,
    """
    TEXT: Cellulose (C <sub>6</sub> H <sub>10</sub> O <sub>5</sub> ) <sub>n</sub> is one of the most ubiquitous organic polymers on the planet. It is a significant structural component of the primary cell wall of green plants, various forms of algae and oomycetes. It is a polysaccharide consisting of a linear chain of several hundred to many thousands of β(1 → 4) linked d-glucose units. There are various extraction procedures for cellulose developed by using different processes like oxidation, etherification and esterification which convert the prepared celluloses in to cellulose derivatives. Since it is a non-toxic, bio-degradable polymer with high tensile and compressive strength, it has widespread use in various fields such as nanotechnology, pharmaceutical industry, food industry, cosmetics, textile and paper industry, drug-delivery systems in treating cancer and other diseases. Micro-crystalline cellulose in particular is among the most frequently used cellulose derivatives in the food, cosmetics, pharma industry, etc. and is an important excipient due to its binding and tableting properties, characterized by its plasticity and cohesiveness when wet. Bacterial cellulose's high dispensability, tasteless and odourless nature provides it with lot of industrial applications. Currently, about half of the waste produced in India contains about 50% cellulose which can be used productively. This chapter deals with the chemistry of cellulose, its extraction and its properties which help various industries to make the most of it.
    { "application": "['cosmetics', 'textile', 'paper', 'drug-delivery', 'food', 'cosmetics']" }

    TEXT: The structure of cellulose has been constantly a subject requiring intensive research as it is formed by the hydrogen bonds between the network of hydroxy groups. The progress was for more than a 100 years of intensive development on structure analysis methods like electron microscopy, X-ray diffraction and high resolution solid state NMR spectroscopy. The complete detailed analysis is required for the procedures of synthetic reactions and cellulose based manmade products with extensive applications. The structure of cellulose as depicted in Figure 2 consists of hydroxyl groups of β-1,4-glucan cellulose at C2, C3 and C6. The CH <sub>2</sub> OH group is positioned relative to the C4 and C5 bonds along with a shear relativity with O5–C5 bonds. The solid state is equally likely to be represented in the crystalline (high order) and amorphous (low order). The crystal structure in particular is determined by the X-ray diffraction using a monoclinic unit cell which is made up of two cellulose chains in a parallel orientation and two fold screw axis. The investigations with respect to the electron microbeam diffraction, combined X-ray and neutron diffraction have clearly indicated that the cellulose crystalline structures have a triclinic and monoclinic unit cell. The schematic representations of the I <sub>β</sub> crystal structure, in Figure 3, indicate the two intramolecular chain-stiffening hydrogen bonds. The recent researches on the I <sub>β</sub> crystal structure have different H-bonds and different conformations of neighbouring chains. The thermodynamically stable cellulose II can occur in other forms of crystal structures and is the most stable form of cellulose. The cellulose I can be treated with aqueous sodium hydroxide to form cellulose II.
    { "application": "['cellulose based manmade products']" }

    TEXT: From the advent of novel drug delivery systems, cellulose based models seemed like strong candidates due to their projected benefits. Since then various advances have been made with the aim to bring its use to common practice. There are still many hurdles to cross before this becomes a reality. Cellulose based drug delivery is an important step in green and sustainable pharmacy which focuses on toxicity reduction, biodegradability and less hazardous synthesis with respect to drugs and drug delivery systems. A very brief overview of the primary ways in which it is used is provided here. Cellulose nanocrystals (CNCs) have the potential to acquire a negative charge during hydrolysis. This coupled with their large surface area allow them to bind ionizable drugs such as tetracycline and doxorubicin permitting optimum dosing control. Sites for surface modification for multiple chemicals are provided by the multitude of surface hydroxyl groups. This is used in case of non-ionized or hydrophobic drugs which do not generally bind to cellulose. The open pore structure and high surface area of CNC based aerogels provide increased drug loading capacity and drug bioavailability. Extremely porous aerogel scaffolds were reported to attain sustained drug release.
    { "application": "['aerogel scaffolds', 'drug release']" }

    TEXT: Regioselectively substituted (position 2, 3 or 6 of the AGU) cellulose phenylurethanes with F, Cl, or CH <sub>3</sub> groups in the phenyl ring form lyotropic liquid-crystalline mesophases in highly concentrated solutions, the structure and optical properties of which depend strongly on the site of substitution, as well as on the concentration and temperature of the solution. The photo-cross-linking of cellulose-(3-chlorophenyl)-urethanes in mixtures with acrylate monomers produces semi-interpenetrating polymer networks, which can change their selective reflection under compression. Cellulose urethanes with azo-dye substituents and acrylates of hydroxypropyl cellulose are other well-analyzed lyotropic liquid-crystalline cellulose products. The latter form gels in water through photo-cross-linking, and their resulting color is determined by the water content. The optical properties that can be controlled by the pitch of cholesteric phases open up important fields of application, such as color pigments in car paints and as copy protection color for document papers.
    { "application": "['car paints', 'document papers']" }

    TEXT: Solid dosage forms including pills, tablets, granules, pellets, microcapsules and spherules can be coated, usually with the aim to protect the drug from adverse environmental factors such as humidity, oxygen, enzymatic or acidic degradation. Coating may also be used to facilitate drug delivery systems with altered release mechanisms such as delayed release, extended release, step-by-step release, pulsatile release and sustained release. Derivatives of cellulose such as esters and ethers are also extensively used as coating materials. In the process of solid dosage form manufacture by direct compression, a problem that frequently occurs is low compactability of the drug, this is more seen more frequently when the amount of drug in the formulation exceeds 30%. Many attempts are being made to reduce the price of the final product by experimenting with various starting materials and test conditions.
    { "application": "['pills', 'tablets', 'granules', 'pellets', 'microcapsules', 'spherules', 'drug', 'coating materials', 'drug', 'drug']" }

    TEXT: Cellulose derivatives have also been researched in terms of drug delivery. For instance, cellulose acetate has been successfully used in several HIV drugs, five flavonoids, one pain reliever and two antibiotics among others. Hydroxypropyl methylcellulose has been used in oral drug delivery formulations.
    { "application": "['HIV drugs', 'flavonoids', 'pain reliever', 'antibiotics']" }
    
    TEXT: Cellulose II (see Sect. 3.3) shows a different hydrogen bonding system. Because of the existence of an intermolecular hydrogen bond between the OH groups of C6 and C2 of another chain, the intramolecular bonding of OH in C2 is avoided and an intermolecular hydrogen bond of OH-C2 to OH-C2 of the next chain is formed. In comparison to cellulose I, the cellulose II molecules are more densely packed and strongly interbonded and, therefore, cellulose II is less reactive, as commonly observed. Figure 3 shows a scheme of the hydrogen bonding system in cellulose I and II.
    { "application": "[]" }
    """,
    """
    TEXT: From the advent of novel drug delivery systems, cellulose based models seemed like strong candidates due to their projected benefits. Since then various advances have been made with the aim to bring its use to common practice. There are still many hurdles to cross before this becomes a reality. Cellulose based drug delivery is an important step in green and sustainable pharmacy which focuses on toxicity reduction, biodegradability and less hazardous synthesis with respect to drugs and drug delivery systems. A very brief overview of the primary ways in which it is used is provided here. Cellulose nanocrystals (CNCs) have the potential to acquire a negative charge during hydrolysis. This coupled with their large surface area allow them to bind ionizable drugs such as tetracycline and doxorubicin permitting optimum dosing control. Sites for surface modification for multiple chemicals are provided by the multitude of surface hydroxyl groups. This is used in case of non-ionized or hydrophobic drugs which do not generally bind to cellulose. The open pore structure and high surface area of CNC based aerogels provide increased drug loading capacity and drug bioavailability. Extremely porous aerogel scaffolds were reported to attain sustained drug release.
    { "process": "['Cellulose based drug delivery', 'toxicity reduction', 'biodegradability', 'less hazardous synthesis', 'hydrolysis', 'surface modification']" }

    TEXT: Celluloses from different sources possess comparable crystallinity (i.e., modifications of cellulose I). However, solid state <super>13</super> C-NMR studies revealed that cellulose can crystallize with varying proportions of two different phases, named cellulose I <sub>α</sub> and I <sub>β</sub> . Plant cellulose mainly consists of cellulose I <sub>β</sub> , whereas cellulose produced by primitive organisms crystallizes in the I <sub>α</sub> phase. The monoclinic unit cell of cellulose I <sub>α</sub> with a space group P2 <sub>1</sub> consists of two cellulose molecules, each containing a cellobiose unit in the 002 corner plane and 002 center plane in a parallel fashion. Cellulose I <sub>β</sub> corresponds to a triclinic symmetry with space group P <sub>1</sub> containing one chain in the unit cell, as schematically displayed in Fig. 6a.
    { "process": "['modifications of cellulose I', 'solid state <super>13</super> C-NMR', 'crystallize', 'crystallizes']" }

    TEXT: As a result of the extended hydrogen bonds between the cellulose chains, special media and procedures must be applied to dissolve cellulose. Today, solvents are divided into derivatizing solvents (forming covalent bonds of low stability with the polymer) and nonderivatizing solvents (interacting only physically with the polymer). At the industrial scale, cellulose nitrate as a soluble and, thus, formable cellulose derivative can be used. It should be pointed out that cellulose nitrate is a relatively stable cellulose derivative so introduction of ester moieties for "derivatizing dissolution" is somewhat questionable, although regeneration is easy to achieve. The invention of a mixture of copper(II) hydroxide and aqueous ammonia for dissolving cellulose, with subsequent precipitation in dilute sulfuric acid, was followed by probably the most important large-scale technical process in fiber production, the viscose process. Cellulose is transformed into cellulose xanthogenate, with subsequent spinning of the solution in aqueous sodium hydroxide. The Lyocell process is an environmentally friendly alternative to the viscose process, whereby cellulose is dissolved physically in N-methylmorpholine-N-oxide monohydrate and regenerated in water.
    { "process": "['procedures', 'derivatizing dissolution', 'regeneration', 'fiber production', 'viscose process', 'spinning', 'Lyocell process', 'viscose process']" }

    TEXT: The first ionic liquids (ILs) used for esterification of cellulose were Nalkylpyridinium halides, especially N-ethylpyridinium chloride (EPyCl) and N-benzylpyridinium chloride (BPyCl). Nevertheless, the most promising ILs for the modification of cellulose are the salts of 1-alkyl-3-methylimidazolium. In 2002, it was shown that such ILs could open new paths for the shaping of polysaccharides. Additionally, they could lead to commercially relevant routes toward homogeneous cellulose chemistry, which would significantly broaden the number of tailored cellulose derivatives. Meanwhile, a huge number of cellulose-dissolving ILs are now known and discussed in various recent reviews (e.g., and references cited therein), and the number of reported low melting organic salts is growing rapidly (Fig. 22). Nevertheless, according to the literature and our own experience, cellulose can be dissolved in ILs with imidazolium, ammonium, and pyridinium. Only organic salts with asymmetric cations give melts that can interact with the backbone of cellulose. Neither sulfonium nor phosphonium salts have so far been able to dissolve cellulose. Dissolution of cellulose in pyridinium salts must be performed under protective gas otherwise degradation results.
    { "process": "['esterification of cellulose', 'modification of cellulose', 'shaping of polysaccharides', 'Dissolution of cellulose', 'degradation']" }
    
    TEXT: Figure 1 shows the molecular structure of cellulose as a carbohydrate polymer generated from repeating b-d-glucopyranose molecules that are covalently linked through acetal functions between the equatorial OH group of C4 and the C1 carbon atom (b-1,4-glucan), which is, in principle, the manner in which cellulose is biogenetically formed. As a result, cellulose is an extensive, linear-chain polymer with a large number of hydroxy groups (three per anhydroglucose (AGU) unit) present in the thermodynamically preferred <super>4</super> C <sub>1</sub> conformation. To accommodate the preferred bond angles of the acetal oxygen bridges, every second AGU ring is rotated 1808 in the plane. In this manner, two adjacent structural units define the disaccharide cellobiose.
    { "process": "[]" }
    """,
    """
    TEXT: The pulp was first passed through a high-speed disperser to ensure uniform consistency. It was then treated in a heated twin-screw extruder which allowed precise control over the cellulose blend. A fiber analyzer and optical microscope were used for measurement of the fiber morphology. After processing, samples were dried using a vacuum oven and finally examined with a scanning electron microscope.
    { "equipment": "['high-speed disperser', 'twin-screw extruder', 'fiber analyzer', 'optical microscope', 'vacuum oven', 'scanning electron microscope']" }
    """,
    """
    TEXT: The sample exhibited a tensile strength of 45 MPa and an elongation at break of 6.3%. Additionally, the water contact angle was measured to be 78°, indicating moderate hydrophobicity. The thermal stability was characterized by a degradation temperature of 320°C. Repeated trials showed consistent tensile strength of 45 MPa and contact angle values.
    { "measurement": "['45 MPa', '320°C', '45 MPa]" }
    """,
    """
    TEXT: The CNCs were extracted from purified cellulose using an acid hydrolysis process. Subsequent analysis was conducted via FTIR and SEM. The FTIR spectra confirmed the absence of lignin, while SEM images revealed the rod-like morphology of the CNCs. Additionally, the resulting nanocellulose was suspended in DI water for further testing.
    { "abbreviation": "['CNCs', 'FTIR', 'SEM', 'FTIR', 'SEM', 'CNCs', 'DI']" }
    """,
]